apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: traefik
        image: traefik:v2.4
        args:
          - "--configFile=/etc/traefik/traefik.yml"
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 8080
        volumeMounts:
          - name: traefik-config
            mountPath: /etc/traefik/traefik.yml
            subPath: traefik.yml
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
