apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: cfpalaciolozano/notification_service:1.0
        ports:
          - containerPort: 8001
        env:
          - name: KAFKA_BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAFKA_BROKER_URL
          - name: KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAFKA_TOPIC
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
