apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  MYSQL_USER: "dXNlcg=="
  MYSQL_PASSWORD: "c2VjcmV0"   
  MYSQL_ROOT_PASSWORD: "cm9vdHNlY3JldA==" 
  GRAFANA_PASSWORD: "YWRtaW4=" 
